"""Add avatar_url field to User model

Revision ID: 42a9f0364fc5
Revises:
Create Date: 2025-12-07 19:06:15.228282

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '42a9f0364fc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像URL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###